<a href="https://colab.research.google.com/github/VigneshGondrawar/numpy1/blob/main/Iterate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array(range(10,31,2))
print(a,type(a))
print("Dimension of a=",a.ndim)

[10 12 14 16 18 20 22 24 26 28 30] <class 'numpy.ndarray'>
Dimension of a= 1


In [ ]:
for i in a:
  print(i)

10
12
14
16
18
20
22
24
26
28
30


In [ ]:
#Iterate the 2-D Array data
a=np.array(range(10,33,2)).reshape(3,4)
print(a,type(a))
print("Dimension of a=",a.ndim)

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]] <class 'numpy.ndarray'>
Dimension of a= 2


In [ ]:
for i in a:
  for j in i:
    print(j)

10
12
14
16
18
20
22
24
26
28
30
32


In [ ]:
#Iterate the 3-D Array data
a=np.arange(2*3*3).reshape(2,3,3)
print(a,type(a))
print("Dimension of a=",a.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] <class 'numpy.ndarray'>
Dimension of a= 3


In [ ]:
#Iterate the 3-D Array data
for i in a:
  for j in i:
    for g in j:
      print(g)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [ ]:
a=np.array(range(10,31,2))
print(a,type(a))
print("Dimension of a-",a.ndim)
print("----------------------------------------------")
for i in np.nditer(a):
  print(i)

[10 12 14 16 18 20 22 24 26 28 30] <class 'numpy.ndarray'>
Dimension of a- 1
----------------------------------------------
10
12
14
16
18
20
22
24
26
28
30


In [ ]:
a=np.array(range(10,33,2)).reshape(3,4)
print(a,type(a))
print("Dimension of a=",a.ndim)
print("----------------------------------------")
for i in np.nditer(a):
  print(i)


[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]] <class 'numpy.ndarray'>
Dimension of a= 2
----------------------------------------
10
12
14
16
18
20
22
24
26
28
30
32


In [ ]:
a=np.array(range(1,17,1)).reshape(2,2,2,2)
print(a,type(a))
print("Dimension of a=",a.ndim)
print("-------------------------------------------")
for i in np.nditer(a):
  print(i)


[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]] <class 'numpy.ndarray'>
Dimension of a= 4
-------------------------------------------
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
a=np.array(range(1,13,1)).reshape(2,3,2)

In [ ]:
a=np.array(range(10,21,1))
print(a,type(a))
print("Dimension of a=",a.ndim)

[10 11 12 13 14 15 16 17 18 19 20] <class 'numpy.ndarray'>
Dimension of a= 1


In [ ]:
a=np.array(range(10,22,1)).reshape(2,2,3)
print(a,type(a))
print("Dimension of a=",a.ndim)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>
Dimension of a= 3


In [ ]:
a=np.array(range(10,22,1)).reshape(2,2,3)
print(a,type(a))
print("Dimension of a=",a.ndim)
for i in np.ndenumerate(a):
  print(i)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>
Dimension of a= 3
((0, 0, 0), np.int64(10))
((0, 0, 1), np.int64(11))
((0, 0, 2), np.int64(12))
((0, 1, 0), np.int64(13))
((0, 1, 1), np.int64(14))
((0, 1, 2), np.int64(15))
((1, 0, 0), np.int64(16))
((1, 0, 1), np.int64(17))
((1, 0, 2), np.int64(18))
((1, 1, 0), np.int64(19))
((1, 1, 1), np.int64(20))
((1, 1, 2), np.int64(21))


In [ ]:
a=np.array(range(10,22,1)).reshape(3,4)
print(a,type(a))
print("Dimension of a=",a.ndim)
for i in np.ndenumerate(a):
  print(i)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]] <class 'numpy.ndarray'>
Dimension of a= 2
((0, 0), np.int64(10))
((0, 1), np.int64(11))
((0, 2), np.int64(12))
((0, 3), np.int64(13))
((1, 0), np.int64(14))
((1, 1), np.int64(15))
((1, 2), np.int64(16))
((1, 3), np.int64(17))
((2, 0), np.int64(18))
((2, 1), np.int64(19))
((2, 2), np.int64(20))
((2, 3), np.int64(21))


In [ ]:
a=np.array(range(10,22,1)).reshape(3,4)
print(a,type(a))
print("Dimension of a=",a.ndim)
for i in np.ndenumerate(a):
  print(i[1])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]] <class 'numpy.ndarray'>
Dimension of a= 2
10
11
12
13
14
15
16
17
18
19
20
21


In [ ]:
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(2,3,2)
print(a,type(a))
print("Dimension of a=",a.ndim)
for i in np.ndenumerate(a):
  print("MattrixNo:{} Row:{} Col:{} Value:{}",)

[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 25]
  [35 45]]] <class 'numpy.ndarray'>
Dimension of a= 3
10
20
30
40
50
60
70
80
90
25
35
45


In [2]:
#Iterate the 2-D Array data
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(2,3,2)
print(a,type(a))
print("Dim of a=",a.ndim)
print("-----------------------------------")
for x in np.ndenumerate(a):
    print("MatrixNo:{} Row:{} Col:{} Value:{}".format(x[0][0],x[0][1],x[0][2],x[1]))

[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 25]
  [35 45]]] <class 'numpy.ndarray'>
Dim of a= 3
-----------------------------------
MatrixNo:0 Row:0 Col:0 Value:10
MatrixNo:0 Row:0 Col:1 Value:20
MatrixNo:0 Row:1 Col:0 Value:30
MatrixNo:0 Row:1 Col:1 Value:40
MatrixNo:0 Row:2 Col:0 Value:50
MatrixNo:0 Row:2 Col:1 Value:60
MatrixNo:1 Row:0 Col:0 Value:70
MatrixNo:1 Row:0 Col:1 Value:80
MatrixNo:1 Row:1 Col:0 Value:90
MatrixNo:1 Row:1 Col:1 Value:25
MatrixNo:1 Row:2 Col:0 Value:35
MatrixNo:1 Row:2 Col:1 Value:45
