<a href="https://colab.research.google.com/github/VigneshGondrawar/numpy1/blob/main/shuffle2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Syntax:	numpy.random.shuffle(ndarrayobject)
import numpy as np
a=([10,20,30,40,50])
print("before shuffle() content of a={} type={} and ID={}".format(a,type(a),id(a)))
np.random.shuffle(a)
print("After Shuffle() content of a={} type={} and ID={}".format(a,type(a),id(a)))

before shuffle() content of a=[10, 20, 30, 40, 50] type=<class 'list'> and ID=132291640717440
After Shuffle() content of a=[40, 10, 20, 30, 50] type=<class 'list'> and ID=132291640717440


In [3]:
np.random.shuffle(a)
print("After Shuffle() content of a={} type={} and ID={}".format(a,type(a),id(a)))

After Shuffle() content of a=[40, 10, 30, 20, 50] type=<class 'list'> and ID=132291640717440


In [4]:
np.random.shuffle(a)
print("After shuffle() content of a={} type={} and ID={}".format(a,type(a),id(a)))

After shuffle() content of a=[10, 40, 20, 50, 30] type=<class 'list'> and ID=132291640717440


In [5]:
for i in range(len(a)):
  np.random.shuffle(a)
  print(a)

[40, 30, 50, 10, 20]
[10, 40, 30, 50, 20]
[20, 30, 40, 50, 10]
[30, 40, 20, 10, 50]
[50, 10, 30, 20, 40]


In [8]:
for i in range(len(a)):
  np.random.shuffle(a)
  print(a,id(a))

[10 30 20 40 50] 132291279865968
[30 20 10 50 40] 132291279865968
[40 10 30 20 50] 132291279865968
[30 50 10 40 20] 132291279865968
[30 50 40 10 20] 132291279865968


In [10]:
#Syntax:varname=numpy.random.permutation(ndarrayobject)
a=np.array([10,20,30,40,50])
print("before permutation content of a={} type={} and ID={}".format(a,type(a),id(a)))
b=np.random.permutation(a)
print("After permutation content of a={} type={} and ID={}".format(a,type(a),id(a)))
print("After permutation content of a={} type={} and ID={}".format(b,type(b),id(b)))

before permutation content of a=[10 20 30 40 50] type=<class 'numpy.ndarray'> and ID=132290891139280
After permutation content of a=[10 20 30 40 50] type=<class 'numpy.ndarray'> and ID=132290891139280
After permutation content of a=[50 10 20 30 40] type=<class 'numpy.ndarray'> and ID=132290891792176


In [11]:
b=np.random.permutation(a)
print("After permutation content of a={} type={} and ID={}".format(b,type(b),id(b)))

After permutation content of a=[40 10 20 50 30] type=<class 'numpy.ndarray'> and ID=132291279865968


In [12]:
b=np.random.permutation(a)
print("After permutation content of a={} type={} and ID={}".format(b,type(b),id(b)))

After permutation content of a=[10 30 20 40 50] type=<class 'numpy.ndarray'> and ID=132290891792176


In [15]:
for i in range(len(a)):
  b=np.random.permutation(a)
  print(b,id(b))

[10 50 40 20 30] 132290891141296
[10 30 20 50 40] 132290891141488
[40 10 30 20 50] 132290891792176
[50 30 20 40 10] 132290891141488
[10 40 50 30 20] 132290891792176
